### ISSUE TITLE
how to use graphql api with this package

### ISSUE THREAD

**Issue by eafarooqi** [signifly/laravel-shopify#26]
hi, 

can we use GraphQL Admin Api. I see there is one method `$shopify->graphQl()`
can you please provide with some example, as its not in the documentation.

**Comment by achatainga** [comment]
This is what I did to make it work:
I create a folder `Classes` under app (app/Classes) and made a class: `MyShopify` which extends Shopify:
```
<?php
namespace App\Classes;

use Signifly\Shopify\Shopify;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;
use App\Traits\MakesGraphqlRequests;

class MyShopify extends Shopify
{
    use MakesGraphqlRequests;

    public function graphQl(): PendingRequest
    {
        return $this->httpClient ??= Http::baseUrl($this->getBaseUrl() . "/graphql.json")
            ->withHeaders(['X-Shopify-Access-Token' => $this->password]);
    }

    private function isJson($string) {
        json_decode($string);
        return json_last_error() === JSON_ERROR_NONE;
     }
}
```

I created a folder `Traits` under app (app/Traits) and made a trait: `MakesGraphqlRequests`:
```
<?php

namespace App\Traits;

use Illuminate\Http\Client\Response;
use Signifly\Shopify\Exceptions\ErrorHandlerInterface;

trait MakesGraphqlRequests
{
    public function graphQlRequest($query = null) {
        $json = $this->isJson($query) ? $query : json_encode($query);
        
        $response = $this->graphQl()->post("", [ "query" => $query ]);

        $this->handleErrorResponse($response);

        return $response;
    }

    private function handleErrorResponse(Response $response): void
    {
        $this->lastResponse = $response;

        app(ErrorHandlerInterface::class)->handle($response);
    }
}
```

I edited `composer.json` to load my class and trait like this adding the following lines under autoload->psr-4 (ignore the lines under files since I have a file to add helper functions... you just need to add the last two lines):
```
"autoload": {
        "files": [
            "app/helpers.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "App\\Classes\\": "app/Classes",
            "App\\Traits\\": "app/Traits"
        }
    },
```

Finally I ran the command
`composer dump-autoload`

Usage:
At the top of your controller put:
`use App\Classes\MyShopify;`
Initialize MyShopify class instead of Shopify:
```
$shopify = new MyShopify(
    env('SHOPIFY_API_KEY'),
    env('SHOPIFY_PASSWORD'),
    env('SHOPIFY_DOMAIN'),
    env('SHOPIFY_API_VERSION')
);
```
Write your query for example: **Notice that the query starts with '**
`$graphQLquery = '{products(first:10){edges{node{title createdAt handle id onlineStorePreviewUrl onlineStoreUrl options(first:10){id name position values}seo{description title}status tags}}}}';`

Or you can use an online json encoder which would also work:

`$graphQLquery = "{products(first:10){edges{node{title createdAt handle id onlineStorePreviewUrl onlineStoreUrl options(first:10){id name position values}seo{description title}status tags}}}}";`

and get the result:

```
$result = $this->shopify->graphQlRequest($graphQLquery);
dd($result);
```

**Comment by savage-eagle** [comment]
Hi, the previous code is missing sending the varaibles. How is possible to send graphql with variables?

Trying to send 
```php
$query = 'mutation orderMarkAsPaid { orderMarkAsPaid(input: $input) { order { id } userErrors { field message }}}';

$data = [
	"query" => $query,
	"variables" => [
		'input' => [
			"id" => $graphQlApiId,
		],
	],
];

$graphQl = $shopify->graphQl();
$response = $graphQl->post("", $data);
```

The error that I'm getting is `Variable $input is used by orderMarkAsPaid but not declared`. 

Any idea how to fix? Thanks.

**Comment by Israel5** [comment]
Hi @eafarooqi,
Do you still have questions about how to use GraphQL with this package?

@achatainga provided a very good example of how you use it.

For simplicity, you can also instantiate the Laravel Shopify class and then call GraphQL directly like in the example below:

```php
// Instantiate the Shopify class
$shopify = new Shopify(
   env('SHOPIFY_API_KEY'),
   env('SHOPIFY_PASSWORD'),
   env('SHOPIFY_DOMAIN'),
   env('SHOPIFY_API_VERSION')
);

// Return the first 10 products
return $shopify->graphQl()->post('', ['query' => "
   {
       products(first: 10) {
           edges {
               node {
                   id
                   title
               }
           }
       }
   }
"]);
```

And here is an example of the output:
<img width="575" alt="Screen Shot 2022-09-16 at 11 40 17 AM" src="https://user-images.githubusercontent.com/63180786/190677745-4ad20641-ac17-4eef-8309-53824bed713e.png">

For now I'll close this issue, but please, let us know if you still have questions.
