### ISSUE TITLE
url is changed suddenly and now every connection is failing ! 

### ISSUE THREAD

**Issue by ahmedbashirdev** [signifly/laravel-shopify#40]
![SCR-20230109-rq0](https://user-images.githubusercontent.com/89787876/211375661-2d3ad8c5-e6d7-4086-be95-2281e9dc9377.png)

**Comment by joecampo** [comment]
I've found that this is because the constructor on the Shopify class is missing the `$password` param in the constructor. It is correct in the 1.x branch. @Razorsheep would you be able to merge that branch into main before tagging the update for Laravel 10? Sorry to ping & appreciate you upgrading this :)

**Comment by Kalo79** [comment]
The documentation still says that the client is initialized with:
$shopify = new Shopify(
    env('SHOPIFY_API_KEY'),
    env('SHOPIFY_PASSWORD'),
    env('SHOPIFY_DOMAIN'),
    env('SHOPIFY_API_VERSION')
);


However, since version 1.2.2 the Shopify class no longer has a "password" property and the password parameter is gone from the __constructor.

The documentation needs an update.

Revert back to version 1.2.1 until the documentation is updated.

**Comment by joecampo** [comment]
As Kalo79 mentioned, the constructor was changed to use `api access token` (most likely named `SHOPIFY_PASSWORD` in your .env) vs. the old way of using `api access key` & `secret key`.

You'll just simply want to update your constructor and everything should work as normal :)

**Comment by Kalo79** [comment]
Actually I was not able to make it work and had to revert back to version 1.2.1
Can someone please update the documentation (https://www.notion.so/signifly/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa)?

**Comment by Razorsheep** [comment]
Updated the docs (https://www.notion.so/signifly/Laravel-Shopify-424709fa6dd84defb0879ab8a1cb29fa) to reflect the new way to initialize the Shopify Client:

## Initializing the Client

```php
use Signifly\Shopify\Shopify;

$shopify = new Shopify(
    env('SHOPIFY_ACCESS_TOKEN'),
    env('SHOPIFY_DOMAIN'),
    env('SHOPIFY_API_VERSION')
);
```
